name: postgres-ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GOMONOLITH_PATH: /home/runner/work/go-monolith/go-monolith
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: gomonolithofficialtest
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: gomonolithofficialtest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: go build -tags "postgres" -v .
      - name: Test
        run: make test TAGS=postgres TEST_ENVIRONMENT=test_postgres
