name: sqlite-ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  UADMIN_PATH: /home/runner/work/go-monolith/go-monolith
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: go build -v .
      - name: Test
        run: make test TEST_ENVIRONMENT=test_sqlite
